### ISSUE TITLE
remove old ocp cluster

### ISSUE THREAD

**Issue by csantanapr** [cloud-native-toolkit/automation-modules#208]
remove from catalog.yaml

```
- name: OpenShift Cluster
        id: github.com/cloud-native-toolkit/terraform-k8s-ocp-cluster
        aliases:
          - github.com/cloud-native-toolkit/terraform-ocp-cluster
        metadataUrl: >-
          https://cloud-native-toolkit.github.io/terraform-k8s-ocp-cluster/index.yaml
        group: openshift
```
